### ISSUE TITLE
大佬可以帮忙看下yarn tauri build这个报错吗

### ISSUE THREAD

**Issue by yuhengZheng1229** [shiyutim/tickets#1]
![1685963929720](https://github.com/shiyutim/tickets/assets/45554184/afb2e0e9-a187-4898-99ab-5d352decf660)

**Comment by shiyutim** [comment]
是不是你的 npm config配置有问题，删除重新配置下呢

**Comment by yuhengZheng1229** [comment]
> 是不是你的 npm config配置有问题，删除重新配置下呢

可以的，将.npmrc删了就可以了，谢谢
