### ISSUE TITLE
feedback：可选席位档次功能

### ISSUE THREAD

**Issue by itsAnstar** [shiyutim/tickets#112]
现在选择场次之后好像无法选择席位档次，请问是否有计划新增这个功能呢

![123](https://github.com/shiyutim/tickets/assets/65763757/871fc1de-6eb4-41aa-979c-5ecd18a1bd49)

**Comment by itsAnstar** [comment]
兄弟们，h5的好像都拒绝响应了

**Comment by shiyutim** [comment]
目前已经不能用了，暂时不会更新了。

**Comment by itsAnstar** [comment]
> 目前已经不能用了，暂时不会更新了。

我留意到了h5页面的情况了
祝好☕️
