### ISSUE TITLE
没找到itemid，只找到id

### ISSUE THREAD

**Issue by yimiyg** [shiyutim/tickets#140]
报错：检测到商品详情获取失败，将再次重新获取，如果再次失败，则停止购票。

**Comment by yimiyg** [comment]
哦好吧我懂了，pc不行，得转成手机的页面大小才能自动换成itemid

**Comment by xiaomingtx12** [comment]
检测到商品详情获取失败，将再次重新获取，如果再次失败，则停止购票。这个解决了吗
