### ISSUE TITLE
开售时间获取错误

### ISSUE THREAD

**Issue by anan-li** [shiyutim/tickets#18]
开售时间不对，好像只能获取整点的

**Comment by shiyutim** [comment]
麻烦提供下itemId，和页面截图

**Comment by LitSummer** [comment]
整点的是正确的，itemId=718335834447 ![error.png](https://s2.loli.net/2023/06/09/IsGBCUtaSydfEiA.png)

**Comment by LitSummer** [comment]
看了下，接口返回的时间是202306101700 ，实际时间是 202306101717

**Comment by zsszyx** [comment]
我好像也遇到了这个问题
![image](https://github.com/shiyutim/tickets/assets/78109473/b1e3da19-bd1e-4cf6-9f5b-975deccadc51)
![image](https://github.com/shiyutim/tickets/assets/78109473/3775855a-7c43-457d-8ca2-ac841daab8a6)

**Comment by shiyutim** [comment]
已修复
