### ISSUE TITLE
error; FAIL_SYS_USER_VALIDATE; RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试

### ISSUE THREAD

**Issue by 18170967136** [shiyutim/tickets#19]
刚刚使用它买了一次票，第二次的时候，就出现这个错误了。是不是不能频繁进行购票呢？否则会被拦截

**Comment by shiyutim** [comment]
这种情况是被大麦限制了，正常情况下，应该不会第二次就限制的。这种情况退出登录重新登录下。或者换个浏览器登录
