### ISSUE TITLE
请问怎么付款呢？现在已经显示倒计时抢票了

### ISSUE THREAD

**Issue by puhuajiang** [shiyutim/tickets#20]

**Comment by shiyutim** [comment]
付款在你的大麦app的订单页面付款

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: puhua jiang ***@***.***>
发送时间: Thursday, June 8, 2023 6:13:54 PM
收件人: shiyutim/tickets ***@***.***>
抄送: Subscribed ***@***.***>
主题: [shiyutim/tickets] 请问怎么付款呢？现在已经显示倒计时抢票了 (Issue #20)


―

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
