### ISSUE TITLE
【功能预览 & 成功体验】

### ISSUE THREAD

**Issue by huchuansai** [shiyutim/tickets#25]
刚体验了一下，好像能成功（随便挑了一个比较小的场次，不知道比较出名的能不能抢到），还有这个是抢票还是购票软件？如果是抢票丝毫没感觉到抢票的功能，如果是购票，我直接用手机不好吗😂

<img width="1056" alt="image" src="https://github.com/shiyutim/tickets/assets/50079978/44110443-22a9-4af9-912d-6a5d3ae935fa">

**Comment by Roc-egg** [comment]
你找个预售的才有抢票显示啊

**Comment by huchuansai** [comment]
OK 希望READ.me文档写的再丰富点

**Comment by cuiqish88** [comment]
倒计时抢票 我到现在就一次没成功过。。。如果解决不了抢票的这个关键问题，就现在这个软件的已经有的功能来说，有点鸡肋
