### ISSUE TITLE
抢购闪退

### ISSUE THREAD

**Issue by Leung1106** [shiyutim/tickets#27]
抢周杰伦的，到12点自动闪退

**Comment by Victor384** [comment]
闪退+1,到点闪退

**Comment by iAmbitions** [comment]
同样失败了

**Comment by Ankh-L** [comment]
我用的0.3版本，同场次没闪退

**Comment by Victor384** [comment]
> 我用的0.3版本，同场次没闪退

你抢到了吗？提示什么？

**Comment by mstki** [comment]
没闪退，但是没抢到，同时第一次失败后，重选其他场次点击抢购，一直卡在0倒计时

**Comment by iAmbitions** [comment]
是不是本地时间和大麦服务器时间不同步导致失败，两次重试太少了，而且两次重试之后应该设置可以再次抢比较好，同样卡在0倒计时

**Comment by shiyutim** [comment]
闪退应该是获取订单详情的时候，超时之类的，rust painc 了，这个我优化下。然后抢票的逻辑这里我在想想，要不要把购票和抢票的按钮都放出来，重试次数我也在考虑增加

**Comment by haQzz** [comment]
请问，直接下载exe文件运行就可以吗，之前拉了代码但yarn tauri build出错

**Comment by shiyutim** [comment]
已解决
