### ISSUE TITLE
倒计时抢票时间问题

### ISSUE THREAD

**Issue by Roc-egg** [shiyutim/tickets#28]
12:00:01才开始抢票 , 这貌似抢不到吧 , 策略需要修改一下 比如11:59:59开始抢 抢多次, 否则过了1秒才开始怎么可能抢得到?
![image](https://github.com/shiyutim/tickets/assets/15016163/88ed6cf9-6e5a-4c37-9b9f-ec4c14762cb8)
![image](https://github.com/shiyutim/tickets/assets/15016163/614b1d7e-066c-4110-9eae-82976e408810)

**Comment by shiyutim** [comment]
这个时间是创建订单的时间，也就是点击提交订单按钮的确切时间。抢票时间结束后，是需要获取订单详情的，然后才是发送订单。

**Comment by Roc-egg** [comment]
那这样也还是过了1秒 , 如果下单时间是12:00:00应该抢到概率会更高吧

**Comment by Roc-egg** [comment]
感觉日志可以吧毫秒值也加上显示 这样看的更精确一些

**Comment by shiyutim** [comment]
日志到时候我加的完整一些吧，中间流程都补上，提前抢票如果没有到时间，订单详情会获取不到，提前请求我会考虑下。

**Comment by yuhengZheng1229** [comment]
> 日志到时候我加的完整一些吧，中间流程都补上，提前抢票如果没有到时间，订单详情会获取不到，提前请求我会考虑下。

![image](https://github.com/shiyutim/tickets/assets/45554184/839955a0-fa98-47fe-995d-f80ccebe0e69)
我自己本地跑起来项目，然后倒计时时间减了100ms，能卡12:00:00开始，但是跑到createOrder方法耗时3s多，请问下这耗时是正常的吗?

**Comment by shiyutim** [comment]
> 

3秒不太正常，是预售商品然后抢票吗，有可能是一瞬间请求太多。正常来说1秒内就会返回的
