### ISSUE TITLE
看看这个报错

### ISSUE THREAD

**Issue by wdadelege** [shiyutim/tickets#3]
还没开始抢点击场次的时候就报这个错误了
![图片](https://github.com/shiyutim/tickets/assets/54564328/faef63c8-22c0-44e2-a6f9-13f37206f67f)

**Comment by shiyutim** [comment]
预售的票，需要开始售票的时候，才能正常获取每个档位（票价）的信息，相当于进入订单详情页了。这个流程我会优化下

**Comment by jiaming678** [comment]
![image](https://github.com/shiyutim/tickets/assets/134989440/e4c747eb-dc74-4966-b0f7-362cd2ef2cd9)
大佬 这个是什么问题呢
