### ISSUE TITLE
倒计时结束卡在0一直转圈

### ISSUE THREAD

**Issue by JOn2Thou** [shiyutim/tickets#30]
有可能是我电脑本地时间没有校准的缘故吗，我用两台一起都是自动同步过时间的，结果抢票倒计时还相差接近1s，有没有可能可以直接从大麦详情页获取倒数时间。

**Comment by fanchaoo** [comment]
我也是，倒计时最后直接卡在00:00:00就没反应了
<img width="1023" alt="image" src="https://github.com/shiyutim/tickets/assets/10774379/24eb23c0-1809-4475-b30d-157770d6192f">

**Comment by cuiqish88** [comment]
2.0之前 我也是同样情况。升级3.0以后还是会卡，但是在抢票记录里面有抢购记录，但是对于一般倒计时抢票的场次来说，2次失败就不抢了。打个比方最近很火的五月天和周杰伦，你抢2次 页面崩溃就不抢的话，后面再改cookie继续抢的话，你已经来不及了

**Comment by BoyXuanzai** [comment]
建议把重试次数增加到5次
