### ISSUE TITLE
对比了下，抢票界面的时间，好像比大麦的界面时间稍微快了一秒左右

### ISSUE THREAD

**Issue by cquptwmt** [shiyutim/tickets#32]
会不会造成了，抢票时间到了，然后提前发出请求，未能够请求到数据。导致界面一直卡住了没跳动。另外就是请求重购的次数设置为2次可能有点少。可以稍微加一点。五次左右可能好一点。（小白建议）。

**Comment by Garrix75** [comment]
重试三次以后就会持续被盾了

**Comment by cquptwmt** [comment]
用手点提交快，好像也不会。一般的抢票脚本也是在一段时间里一直刷页面。我也不清楚dm拦截机制

**Comment by CleanK1** [comment]
> 会不会造成了，抢票时间到了，然后提前发出请求，未能够请求到数据。导致界面一直卡住了没跳动。另外就是请求重购的次数设置为2次可能有点少。可以稍微加一点。五次左右可能好一点。（小白建议）。

确实会快一点，然后提示商品信息错误

**Comment by cquptwmt** [comment]
老哥，你有dm-ticket那个项目的文件吗？求求。好像博主已经关了docker镜像了。拉不下来了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Garrix75 ***@***.***&gt;
发送时间: 2023年6月9日 14:16
收件人: shiyutim/tickets ***@***.***&gt;
抄送: cquptwmt ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [shiyutim/tickets] 对比了下，抢票界面的时间，好像比大麦的界面时间稍微快了一秒左右 (Issue #32)





 
重试三次以后就会持续被盾了

**Comment by shiyutim** [comment]
抢票时间是根据你们自己本地电脑时间来的，这个我想了一下，准备搞个自己校准的时间差，你们自己对比大麦校准就可以了，自己想提前发包就提前一点。

**Comment by cquptwmt** [comment]
1476558049@qq.com

**Comment by zgq10086** [comment]
哥们，dm-ticket项目能发我一份吗，谢谢了，我的邮箱1363873482@qq.com

**Comment by Ankh-L** [comment]
> 抢票时间是根据你们自己本地电脑时间来的，这个我想了一下，准备搞个自己校准的时间差，你们自己对比大麦校准就可以了，自己想提前发包就提前一点。

这个想法不错的，时间差可以作为界面的一个参数配置

**Comment by cquptwmt** [comment]
等大佬更新





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ankh-L ***@***.***&gt;
发送时间: 2023年6月12日 10:20
收件人: shiyutim/tickets ***@***.***&gt;
抄送: cquptwmt ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [shiyutim/tickets] 对比了下，抢票界面的时间，好像比大麦的界面时间稍微快了一秒左右 (Issue #32)





  
抢票时间是根据你们自己本地电脑时间来的，这个我想了一下，准备搞个自己校准的时间差，你们自己对比大麦校准就可以了，自己想提前发包就提前一点。
  
这个想法不错的，时间差可以作为界面的一个参数配置

**Comment by littleqiang2017** [comment]
> 老哥，你有dm-ticket那个项目的文件吗？求求。好像博主已经关了docker镜像了。拉不下来了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Garrix75 ***@***.***&gt; 发送时间: 2023年6月9日 14:16 收件人: shiyutim/tickets ***@***.***&gt; 抄送: cquptwmt ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [shiyutim/tickets] 对比了下，抢票界面的时间，好像比大麦的界面时间稍微快了一秒左右 (Issue #32) 重试三次以后就会持续被盾了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

帅哥，麻烦给我也发一份，感谢 2456701628@qq.com

**Comment by yyyyGOD** [comment]
> 

老哥可以给我发一份吗，1767733600@qq.com

**Comment by yyyyGOD** [comment]
> > 老哥，你有dm-ticket那个项目的文件吗？求求。好像博主已经关了docker镜像了。拉不下来了 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: Garrix75 _**@**_._**> 发送时间: 2023年6月9日 14:16 收件人: shiyutim/tickets _**@**_.**_> 抄送: cquptwmt _**@**_._**>, Author _**@**_.**_> 主题: Re: [shiyutim/tickets] 对比了下，抢票界面的时间，好像比大麦的界面时间稍微快了一秒左右 (Issue #32) 重试三次以后就会持续被盾了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 给我留个邮箱，我明天发给你

老哥，我也要！1767733600@qq.com

**Comment by xiaoye-2018** [comment]
> 会不会造成了，抢票时间到了，然后提前发出请求，未能够请求到数据。导致界面一直卡住了没跳动。另外就是请求重购的次数设置为2次可能有点少。可以稍微加一点。五次左右可能好一点。（小白建议）。

大佬请问有源码吗dm-ticket 的token  生成源码吗，想研究学习下，有点话麻烦发下1923834375@qq.com,  感谢

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by icbearp** [comment]
2194547774@qq.com
