### ISSUE TITLE
在已经填写cookies的情况下，为什么还让我填写？

### ISSUE THREAD

**Issue by xun666** [shiyutim/tickets#33]
![image](https://github.com/shiyutim/tickets/assets/56375068/f3913671-cece-4ffb-ab93-6cc20c1bdc61)

**Comment by haQzz** [comment]
你要点下面的确定

**Comment by xun666** [comment]
> 你要点下面的确定

绝了，傻了我

**Comment by haQzz** [comment]
是不是只下载了exe安装好执行就可以了？

**Comment by xun666** [comment]
> 是不是只下载了exe安装好执行就可以了？

对，不过具体能不能抢到还没试，等会儿6点有一场，抢枪看看

**Comment by haQzz** [comment]
冲

**Comment by haQzz** [comment]
六点是谁的

**Comment by xun666** [comment]
> 六点是谁的

姚琛

**Comment by haQzz** [comment]
OK

**Comment by qqwwww8741** [comment]
下礼拜试试看能不能抢到五月天的

**Comment by anan-li** [comment]
六点的咋样

**Comment by xun666** [comment]
那会刚好cookie过期，就离谱

**Comment by xun666** [comment]
> > 那会刚好cookie过期，就离谱
> 
> ？？？我也是直接过期，这个是为什么啊

不知道，可能登录太久了？下次我抢票前两分钟再登录看看吧。

**Comment by CleanK1** [comment]
> > > 那会刚好cookie过期，就离谱
> > 
> > 
> > ？？？我也是直接过期，这个是为什么啊
> 
> 不知道，可能登录太久了？下次我抢票前两分钟再登录看看吧。

cookie还会隔几分钟自己刷新啊...

**Comment by CleanK1** [comment]
> > > 那会刚好cookie过期，就离谱
> > 
> > 
> > ？？？我也是直接过期，这个是为什么啊
> 
> 不知道，可能登录太久了？下次我抢票前两分钟再登录看看吧。

我还是最后不到一分钟刷新界面填写的cookies  还是说观影人过期了  我觉得有可能抢快了 快了几毫秒，系统还没放票

**Comment by fanchaoo** [comment]
> 那会刚好cookie过期，就离谱

你是手动点的吗，还是用的倒计时抢票功能啊

**Comment by CleanK1** [comment]
> > 那会刚好cookie过期，就离谱
> 
> 你是手动点的吗，还是用的倒计时抢票功能啊

倒计时功能
