### ISSUE TITLE
获取非整点开抢时间异常

### ISSUE THREAD

**Issue by 1562592475** [shiyutim/tickets#41]
非整点会自动舍弃后面部分，导致倒计时变短

**Comment by 1562592475** [comment]
![image](https://github.com/shiyutim/tickets/assets/79008763/5f9048a1-3604-4d2a-8eb8-a41ca47dec9d)
![image](https://github.com/shiyutim/tickets/assets/79008763/5eb4a27d-f14b-4358-b3f1-52ac4c2971d4)
https://m.damai.cn/damai/detail/item.html?itemId=719269870183&spm=a2o71.search.list.ditem_1

**Comment by awd135awd** [comment]
我也有这个问题，差的就是非整点的部分，这个差了七分钟。

**Comment by 1562592475** [comment]
看了倒计时的逻辑，甚至没发现问题

**Comment by 18170967136** [comment]
是的，抢票时间异常

**Comment by tidysong** [comment]
看了一下是大麦接口问题，它返回的就是整点。可以自己加一个时间校准参数。

**Comment by shiyutim** [comment]
> 看了一下是大麦接口问题，它返回的就是整点。可以自己加一个时间校准参数。

是的，我准备增加一个参数，然后自己校对。至于这个接口，我看下是不是字段取错了

**Comment by xioabei** [comment]
> > 看了一下是大麦接口问题，它返回的就是整点。可以自己加一个时间校准参数。
> 
> 是的，我准备增加一个参数，然后自己校对。至于这个接口，我看下是不是字段取错了

![image](https://github.com/shiyutim/tickets/assets/34567869/b62319cf-7682-4698-bf9c-080e40fdf659)
接口返回的就是没带分钟，我来自己加一个，哈哈哈

**Comment by xioabei** [comment]
> > 看了一下是大麦接口问题，它返回的就是整点。可以自己加一个时间校准参数。
> 
> 是的，我准备增加一个参数，然后自己校对。至于这个接口，我看下是不是字段取错了

![image](https://github.com/shiyutim/tickets/assets/34567869/d1cfacdc-3bb8-4845-a138-fb6eff0f7e36)
完美，看大佬的代码写的还是很厉害的。抢不抢的到另说👍强强强

**Comment by tidysong** [comment]
你们可以研究一下我发现的那个问题，感觉这个问题很大，不过我还没有足够多的机会做更多测试。 #45

**Comment by shiyutim** [comment]
已修复
