### ISSUE TITLE
请教大佬，我本地编译为啥获取商品信息失败，打包的就是好的呢

### ISSUE THREAD

**Issue by xioabei** [shiyutim/tickets#44]
![1686453319167](https://github.com/shiyutim/tickets/assets/34567869/341f2464-1230-487a-876e-a349bf0ce1a1)
![1686453360320](https://github.com/shiyutim/tickets/assets/34567869/8e0f7649-23fb-41cc-b26c-9e5748e0df89)

**Comment by tidysong** [comment]
后端接的是Rust，浏览器调用不上。

**Comment by xioabei** [comment]
请教一下，如何我想本地调试的话，应该怎么操作呢？




高柏祥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shiyutim/tickets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月11日(星期天) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shiyutim/tickets] 请教大佬，我本地编译为啥获取商品信息失败，打包的就是好的呢 (Issue #44)





 
后端接的是Rust，浏览器调用不上。

**Comment by xioabei** [comment]
> 后端接的是Rust，浏览器调用不上。

我本地运行yarn dev命令后，并未打开窗口，是还需要装什么东西吗？

**Comment by xioabei** [comment]
> 后端接的是Rust，浏览器调用不上。

谢谢解惑，我已经调试起来了 原来是加个tauri,之前没玩过这东西，哈哈哈

**Comment by Bunnybeibei** [comment]
@xioabei 楼主你好，我也遇到和你相同的问题，请问你是怎么解决的哈，我没有看懂你的回答，谢谢！

**Comment by shiyutim** [comment]
yarn tauri dev

**Comment by Bunnybeibei** [comment]
> @xioabei 楼主你好，我也遇到和你相同的问题，请问你是怎么解决的哈，我没有看懂你的回答，谢谢！

是因为这个cookie必须是移动端APP的cookie吗？

**Comment by xioabei** [comment]
> > @xioabei 楼主你好，我也遇到和你相同的问题，请问你是怎么解决的哈，我没有看懂你的回答，谢谢！
> 
> 是因为这个cookie必须是移动端APP的cookie吗？

H5的就行
