### ISSUE TITLE
还是有"该渠道不支持购买,请到APP购买"的问题,针对这类有解决办法不

### ISSUE THREAD

**Issue by Lee3S** [shiyutim/tickets#49]
rt所示

**Comment by 1584436652** [comment]
从昨天开始大麦是不是升级了

**Comment by kentzh1** [comment]
脚本泛滥，大麦禁止H5也是情理之中，看能不能解决这个问题了

**Comment by precious7771** [comment]
昨天抢薛之谦合肥的我还能用，朋友的倒计时2分钟重新进来就用不了了

**Comment by 1584436652** [comment]
现在还能用吗 试试薛之谦上海的

**Comment by precious7771** [comment]
不能了
&nbsp;


tanxieqin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月13日(星期二) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shiyutim/tickets] 还是有&quot;该渠道不支持购买,请到APP购买&quot;的问题,针对这类有解决办法不 (Issue #49)





 
现在还能用吗 试试薛之谦上海的

**Comment by shiyutim** [comment]
被禁用就是用不了了，谁也没办法

**Comment by Lee3S** [comment]
> 被禁用就是用不了了，谁也没办法

H5和浏览器端全禁那是真没办法了

**Comment by Lee3S** [comment]
> 现在还能用吗 试试薛之谦上海的

昨天试了任贤齐的,今天试了薛之谦的.这2位都会出现不支持该渠道.
但是其他比较不火爆的票还是可以支持的,估计是专门针对明星做了限制.
不火爆的巴不得脚本把票拿去

**Comment by Roc-egg** [comment]
感觉老实用无障碍才是王道

**Comment by Lee3S** [comment]
> 感觉老实用无障碍才是王道

无障碍是啥意思
