### ISSUE TITLE
error; B-00203-200-031::您选购的商品信息已过期，请重新查询

### ISSUE THREAD

**Issue by jiaming678** [shiyutim/tickets#5]
![image](https://github.com/shiyutim/tickets/assets/134989440/d16395ee-7c9e-4c2a-8f42-602de8661f2c)
麻烦帮忙看看这个问题

**Comment by FantasticSkyBaby** [comment]
同上，抢票倒计时无法开始抢票

**Comment by shiyutim** [comment]
还没开售的商品目前无法购买，需要等到开始购买的时候才能抢票，这个流程后续会优化 自动化下。
