### ISSUE TITLE
被挤爆了，请稍后重试

### ISSUE THREAD

**Issue by zengqingwei-13** [shiyutim/tickets#57]
预售，无论是0秒开始创建订单， 还是2秒开始创建订单， 都是提示 被挤爆了。。
![微信图片_20230617161052](https://github.com/shiyutim/tickets/assets/79566504/c8e8e929-32b7-43ac-9d6d-facced9a6576)
![微信图片_20230617161327](https://github.com/shiyutim/tickets/assets/79566504/55d7f7ee-4502-426d-a25c-3f03d0014a95)

**Comment by shiyutim** [comment]
这个被挤爆了的提示是正常的，就是请求被过滤掉了

**Comment by zengqingwei-13** [comment]
这样子的话，重试次数是不是可以设置多一点， 重试多次限制4次，是因为怕会被限制ip等， 还是token 啥的会失效

**Comment by shiyutim** [comment]
连续请求大约3、4次，就会出现滑块，之后的请求都会被限制，所以再多也没有用

**Comment by zengqingwei-13** [comment]
那如果，加上ip 代理的话，其实还是有可能被限制的？那会不会被过滤掉请求，只能纯看脸了。。。

**Comment by shiyutim** [comment]
这个限制应该是根据 cookie 进行限制的

**Comment by zengqingwei-13** [comment]
那这就难受了呀。
