### ISSUE TITLE
请问如何使用，没太明白

### ISSUE THREAD

**Issue by Jankos-li** [shiyutim/tickets#58]
release里面的那个setup.exe好像安装不了，还是说要下tar.gz自己去打包成.exe呢
![image](https://github.com/shiyutim/tickets/assets/76777318/8b58f314-87f0-4a92-b9db-655015326f1e)

**Comment by shiyutim** [comment]
正常来说 下载对应的 exe 文件就可以了。为啥是 google chrome 未响应？

**Comment by Heelc** [comment]
macbook m1 无法使用 
<img width="260" alt="image" src="https://github.com/shiyutim/tickets/assets/15527886/14315080-b05b-4150-9a71-7bf2c4c93c97">

**Comment by shiyutim** [comment]
> 

mac 用户，使用 .dmg 结尾的程序

**Comment by Heelc** [comment]
> 

thks~

**Comment by Jankos-li** [comment]
> 



> 正常来说 下载对应的 exe 文件就可以了。为啥是 google chrome 未响应？
因为我是google浏览器下载的

**Comment by Jankos-li** [comment]
> 正常来说 下载对应的 exe 文件就可以了。为啥是 google chrome 未响应？

可否发个到我邮箱，我试试呢，978572949@qq.com

**Comment by shiyutim** [comment]
那说明浏览器下载失败，要不挂个梯子下载

**Comment by Jankos-li** [comment]
> er

哈哈，绝了还真是下载的有问题，今天挂个梯子立马下载好了
