### ISSUE TITLE
大佬，请问下抢票的脚本在哪里有资料吗

### ISSUE THREAD

**Issue by AuroraYolo** [shiyutim/tickets#6]

**Comment by shiyutim** [comment]
https://github.com/shiyutim/tickets/releases 这里下载，使用方法看 readme

**Comment by AuroraYolo** [comment]
不是，我想问的下 实现原理。特别请求接口那一部分

**Comment by shiyutim** [comment]
原理就是 大麦移动端是怎么写的，我就是怎么写的。请求接口需要加载一些 sdk脚本，获取必要的参数啥的。我写的代码不难，应该很好理解。

**Comment by shiyutim** [comment]
后续我会写一篇文章，详细讲解过程，不过发布出去应该是很久以后了。

**Comment by AuroraYolo** [comment]
不是，主要不太熟悉rust代码
