### ISSUE TITLE
大佬，为什么倒计时结束，软件没有自动抢票？

### ISSUE THREAD

**Issue by Googasy** [shiyutim/tickets#66]

**Comment by shiyutim** [comment]
看下日志截图

**Comment by Googasy** [comment]
![1687265049665](https://github.com/shiyutim/tickets/assets/128677794/e16d37a5-ed9d-45b0-8a72-ffdf201168da)图里应该在17：17开始抢票，但倒计时结束了没有任何反应，我看抢票按钮也没有变化，于是在17：17：05手动点击抢票，此时票没了，自然也没反应。
上面的警告是我测试抢票功能是否可用，用它抢了些在售的票，还是会失败，很奇怪

**Comment by Googasy** [comment]
![1687265049665](https://github.com/shiyutim/tickets/assets/128677794/db03955c-6d7d-4fe5-a87d-4684c58fe5f4)
如上图所示，软件本该在17：17倒计时结束自动抢票，但我看没有任何反应，于是在17：17：05手动点了抢票，然后估计是票没了，也没任何反应。（上面的报错与本issue无关）
然后我为了检查抢票功能是否可用，抢了些已经在售的票（未售完），会报错被挤爆了，不知道什么原因

**Comment by shiyutim** [comment]
cookie 过期了，倒计时的时候不要时间太长，使用最新的cookie
