### ISSUE TITLE
抢票闪退

### ISSUE THREAD

**Issue by JJUNLANG** [shiyutim/tickets#7]
闪退

**Comment by shiyutim** [comment]
安装最新版本

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: JJUNLANG ***@***.***>
发送时间: Wednesday, June 7, 2023 12:44:05 AM
收件人: shiyutim/tickets ***@***.***>
抄送: Subscribed ***@***.***>
主题: [shiyutim/tickets] 抢票闪退 (Issue #7)


闪退

―
