### ISSUE TITLE
yarn 命令巨慢

### ISSUE THREAD

**Issue by xiaoye-2018** [shiyutim/tickets#70]
已经设置了淘宝镜像，执行yarn tauri  dev， 完全卡死，开了梯子依然巨慢， 有什么解决方案吗

![image](https://github.com/shiyutim/tickets/assets/46118372/bbcf959e-6ae5-4a14-a99d-4943be3ee6c6)

**Comment by xiaoye-2018** [comment]
早上再次测试，如下，看来win可以放弃了
![image](https://github.com/shiyutim/tickets/assets/46118372/12841ce6-83bc-4758-bfa7-ddba68fcb1b4)

**Comment by enchantedlyc** [comment]
我换了清华源可以build成功
