### ISSUE TITLE
突然出现invalid args `ua` for command

### ISSUE THREAD

**Issue by cg666-debug** [shiyutim/tickets#72]
**大佬您好，我目前总共跑了两次，第一次抢票时没啥问题，然后今天上午抢票时突然出现：**
```
订单详情获取失败，请重试; "invalid args `ua` for command `get_ticket_detail`: command get_ticket_detail missing required key ua"
 ```
**通过看源码中找到了getHeaderUaAndUmidtoken函数，ua的值应该是由**
```js
window.__baxia__.getFYModule.getFYToken()
```
**来获取的**
**但是我找不到```window.__baxia__.getFYModule.getFYToken()```是如何执行的，想请问一下ua到底是怎么获取的**

**Comment by cg666-debug** [comment]
先感谢大佬愿意解答，但是我在开始app的时候没有提示任何错误，然后填写完cookie，商品链接之后也没有提示有问题，在开始抢票的时候出现了ua没有获取到。我看到大佬代码上写了注释说data只能使用两次，这跟我把重试次数从2改成5有关系吗

**Comment by shiyutim** [comment]
没关系，每次调用接口都是重新获取的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: cg666-debug ***@***.***>
发送时间: Saturday, July 1, 2023 4:29:33 PM
收件人: shiyutim/tickets ***@***.***>
抄送: shiyu ***@***.***>; State change ***@***.***>
主题: Re: [shiyutim/tickets] 突然出现invalid args `ua` for command (Issue #72)


先感谢大佬愿意解答，但是我在开始app的时候没有提示任何错误，然后填写完cookie，商品链接之后也没有提示有问题，在开始抢票的时候出现了ua没有获取到。我看到大佬代码上写了注释说data只能使用两次，这跟我把重试次数从2改成5有关系吗

―

**Comment by cg666-debug** [comment]
但是在启动程序时没有报错，说明初始化脚本凭证成功了。在获取订单详情时调用getHeaderUaAndUmidtoken却出现获取ua错误

**Comment by shiyutim** [comment]
你手动在控制台调用一下，看看报了什么错误

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: cg666-debug ***@***.***>
发送时间: Saturday, July 1, 2023 5:15:52 PM
收件人: shiyutim/tickets ***@***.***>
抄送: shiyu ***@***.***>; State change ***@***.***>
主题: Re: [shiyutim/tickets] 突然出现invalid args `ua` for command (Issue #72)


但是在启动程序时没有报错，说明初始化脚本凭证成功了。在获取订单详情时调用getHeaderUaAndUmidtoken却出现获取ua错误

―

**Comment by cg666-debug** [comment]
yarn tauri build打包后该怎么运行程序呀，我是直接使用大佬发的安装包安装软件使用的

**Comment by shiyutim** [comment]
看readme

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: cg666-debug ***@***.***>
发送时间: Saturday, July 1, 2023 5:22:54 PM
收件人: shiyutim/tickets ***@***.***>
抄送: shiyu ***@***.***>; State change ***@***.***>
主题: Re: [shiyutim/tickets] 突然出现invalid args `ua` for command (Issue #72)


yarn tauri build打包后该怎么运行程序呀，我是直接使用大佬发的安装包安装软件使用的

―

**Comment by cg666-debug** [comment]
**大佬，我在自己本地跑yarn tauri build命令时一直报错**
```shell
error: failed to run custom build command for `tickets v0.0.0 (D:\Auto_ticket_purchase\Tauri_Tickets\tickets\src-tauri)`

Caused by:
  process didn't exit successfully: `D:\Auto_ticket_purchase\Tauri_Tickets\tickets\src-tauri\target\debug\build\tickets-dd0fa56436a7616f\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop
  cargo:rustc-cfg=dev
  package.metadata does not exist

  --- stderr
  thread 'main' panicked at 'Couldn't to execute windres to compile "D:\Auto_ticket_purchase\Tauri_Tickets\tickets\src-tauri\target\debug\build\tickets-4ae8792db50e6327\out\resource.rc"
 into "D:\Auto_ticket_purchase\Tauri_Tickets\tickets\src-tauri\target\debug\build\tickets-4ae8792db50e6327\out/libresource.a": program not found', C:\Users\EDY\.cargo\registry\src\
index.crates.io-6f17d22bba15001f\embed-resource-2.1.1\src\windows_not_msvc.rs:47:23
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**请问大佬知道这个该怎么解决吗**

**Comment by shiyutim** [comment]
不确定是不是rust包的问题
