### ISSUE TITLE
重试次数会不会有点少

### ISSUE THREAD

**Issue by cuiqish88** [shiyutim/tickets#8]
大麦如果碰到人多的时候，订单会一直失败。2次的话感觉有点不够。是否能修改次数

**Comment by shiyutim** [comment]
因为如果太频繁的请求会被大麦限制，类似这种在app上就会显示滑块之类的，所以目前的重试次数限制为2次。我在考虑一个合理的最大重试次数，使得多次提交订单而不会被限制，然后再开放编辑。

**Comment by cuiqish88** [comment]
是不是可以参考其他脚本的免登录和跳过验证的一些代码完成不限次数

**Comment by shiyutim** [comment]
是通过倒计时自动下单的吗，显示挤爆了应该是对应票档的票卖没了

**Comment by cuiqish88** [comment]
不是倒计时 就是普通的买票都是有现票的情况下。。购票 显示被挤爆了

**Comment by cuiqish88** [comment]
我退出了重进好像也是这样，我试下重新打开网页

**Comment by shiyutim** [comment]
是退出登录，重新登录下。再不行就换一个浏览器，应该就可以了。

**Comment by shiyutim** [comment]
如果方便的话，可以把被限制的cookie  邮箱发我下 shiyutim@outlook.com，我研究下这个限制到底怎么回事
