### ISSUE TITLE
登录过后有证件的号显示观演人证件信息异常，请重新下单

### ISSUE THREAD

**Issue by zhongnanwei** [shiyutim/tickets#9]
![image](https://github.com/shiyutim/tickets/assets/69951084/27b99281-52d3-4a70-be57-a69e4c786985)

**Comment by cuiqish88** [comment]
观演人数和票数是否匹配

**Comment by cuiqish88** [comment]
理论上买几张票  在观演人这里应该就留几个人

**Comment by zhongnanwei** [comment]
明白意思了，试了一下可以抢
